# Generated by Django 4.0.3 on 2022-03-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.RenameField(
            model_name='valuationapi',
            old_name='name',
            new_name='complex',
        ),
        migrations.RenameField(
            model_name='valuationapi',
            old_name='owner',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='valuationapi',
            name='created_at',
        ),
        migrations.AddField(
            model_name='valuationapi',
            name='address_lat',
            field=models.FloatField(default=0.0, verbose_name=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationapi',
            name='address_lon',
            field=models.FloatField(default=0.0, verbose_name=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationapi',
            name='area',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationapi',
            name='building_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationapi',
            name='rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
