# Generated by Django 4.0.3 on 2022-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_mlalgorithmstatus_parent_mlalgorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationapi',
            name='complex',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='valuationapi',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
