# Generated by Django 4.0.3 on 2022-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_valuationapi_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationapi',
            name='security',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valuationapi',
            name='complex',
            field=models.CharField(max_length=200),
        ),
    ]
